  
device: null

exp_name: DQN_pixels

# Environment
# SEEDS: [118398, 676190, 786456, 171936, 887739, 919409, 711872, 442081, 189061, 117840]
env:
  env_name: CartPole-v0
  seed: 118398

# collector
collector:
  total_frames: 2_000_000      # 5_000_016
  frames_per_batch: 128
  eps_start: 1.0
  eps_end: 0.05
  annealing_frames: 200_000 # 3_600_000
  init_random_frames: 10_000
  frame_skip: 4

# policy
policy:
  type: "CNN_MLP"
  cnn_net:
    num_cells: [16, 32, 32] # number of kernel per layer
    kernel_sizes: [6, 4, 3]
    strides: [2, 2, 1]
  mlp_net:
    num_cells: [120, 84]  # Number of units per layer
  activation: "ELU"  # Activation function used in the layers
  use_batch_norm: False

# buffer
buffer:
  buffer_size: 100_000
  batch_size: 256
  scratch_dir: null
  prioritized_replay: False
  alpha: 0.7
  beta: 0.5

# logger
logger:
  backend: wandb
  project_name: dqn_pixels_cartpolev0
  group_name: null
  test_interval: 25_000
  num_test_episodes: 3
  video: False
  mode: "online"
  save_model: False

# Optim
optim:
  lr: 0.0005 # 0.002
  max_grad_norm: 10 # Not used
  weight_decay: 0.00001

# loss
loss:
  gamma: 0.99
  # hard_update_freq: 50
  num_updates: 8
  tau: 0.02 # for soft update # eps=0.995 
  eps: 0.995

