  
device: null

# Environment
# SEEDS: [118398, 676190, 786456, 171936, 887739, 919409, 711872, 442081, 189061, 117840]
env:
  env_name: CartPole-v1
  seed: 118398

# collector
collector:
  total_frames: 100_000
  frames_per_batch: 250
  eps_start: 1.0
  eps_end: 0.04
  annealing_frames: 8_000 # 0.16 % of total frames
  init_random_frames: 1_000

policy:
  type: "MLP"  # Example type, adjust based on your architecture (e.g., CNN, RNN)
  layers: [256, 256]  # Number of units in each layer
  activation: "ReLU"  # Activation function used in the layers

# buffer
buffer:
  buffer_size: 100_000
  batch_size: 64

# logger
logger:
  backend: wandb
  project_name: BER_final_project
  group_name: DQN_CartPole_v1_ER
  exp_name: DQN
  test_interval: 5_000
  num_test_episodes: 5
  video: False

# Optim
optim:
  lr: 0.0023
  max_grad_norm: 10

# loss
loss:
  gamma: 0.99
  hard_update_freq: 10
  num_updates: 128
