  
device: null

exp_name: DQN

# Environment
# SEEDS: [118398, 676190, 786456, 171936, 887739, 919409, 711872, 442081, 189061, 117840]
env:
  env_name: CartPole-v1
  seed: 118398

# collector
collector:
  total_frames: 10000
  frames_per_batch: 10
  eps_start: 1.0
  eps_end: 0.01
  annealing_frames: 1_500
  init_random_frames: 10

# policy
policy:
  type: "MLP"  # Example type, adjust based on your architecture (e.g., CNN, RNN)
  layers: [128, 128]  # Number of units in each layer
  activation: "ReLU"  # Activation function used in the layers

# buffer
buffer:
  buffer_size: 10000 # Check the paper and the effect of the buffer size to have an intuition
  batch_size: 32
  prioritized_replay: False
  alpha: 0.7
  beta: 0.4

# logger
logger:
  backend: wandb
  project_name: BisimulationPER
  group_name: null
  exp_name: DQN
  test_interval: 500
  num_test_episodes: 5
  video: False

# Optim
optim:
  lr: 0.001 # 2.5e-4
  max_grad_norm: 10

# loss
loss:
  gamma: 0.99
  hard_update_freq: 500
  num_updates: 1
