  
device: null

exp_name: DQN_pixels

# Environment
# SEEDS: [118398, 676190, 786456, 171936, 887739, 919409, 711872, 442081, 189061, 117840]
env:
  env_name: GridWorldEnv-v0
  grid_file: "../custom_envs/grid_envs/grid_world2.txt"
  # grid_file: "final_project/custom_envs/grid_envs/grid_world2.txt" # For debugging
  seed: 118398
  enable_mico: False
  start_state: null

# collector
collector:
  total_frames: 100_000 
  frames_per_batch: 128
  eps_start: 0.1
  eps_end: 0.005
  annealing_frames: 520_000 
  init_random_frames: 200 # No warm up only the first batch
  frame_skip: 1

# policy
policy:
  type: "CNN_MLP"
  cnn_net:
    num_cells: [32, 64, 64] # number of kernel per layer
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  mlp_net:
    num_cells: [64, 64]  # Number of units per layer
  activation: "ReLU"  # Activation function used in the layers
  use_batch_norm: False

# buffer
buffer:
  buffer_size: 100_000
  batch_size: 256
  scratch_dir: null
  prioritized_replay: False
  alpha: 0.6
  beta: 0.4
  mico_priority:
    priority_type: "all_vs_all" # "all_vs_all" or "current_vs_next"
    priority_weight: 1.0
    normalize_priorities: False

# logger
logger:
  backend: wandb
  project_name: dqn_pixels_grid_word_v0_sweep
  group_name: null
  test_interval: 10_000
  num_test_episodes: 5
  video: True
  mode: "online" # "online" or "disabled" ("offline" too but not used)
  save_model: False
  window_size: 100
  save_distributions: True
  saving_bisimulation_matrix: True
  saving_exploration_matrix: True
  cumulative_reward: "sum"

# Optim
optim:
  lr: 0.0015 # 0.002
  max_grad_norm: 10
  weight_decay: 0.00001
  eps: 1.5e-4 # default: 1e-08 # rainbow 1.5e-4
  scheduler:
    active: False
    type: "stepLR"
    gamma: 0.4
    step_size: 500_000

# loss
loss:
  double_dqn: False
  gamma: 0.99
  mico_loss:
    mico_weight: 0.01 #0.5
    mico_beta: 0.1
    mico_gamma: 0.99
  target_updater:
    type: "hard"
    hard_update_freq: 50  
    num_updates: 1

  # target_updater:
  #   type: "soft"
  #   eps: 0.995 #0.995 # eps = 1 - tau # Check 0.98
  #   num_updates: 8
