  
device: null

exp_name: DQN_pixels

# Environment
# SEEDS: [118398, 676190, 786456, 171936, 887739, 919409, 711872, 442081, 189061, 117840]
env:
  env_name: CartPole-v0
  seed: 118398

# collector
collector:
  total_frames: 1_100_064 
  frames_per_batch: 64
  eps_start: 0.5 # Set a small exploration to check if the MICO is encouraging exploration (No at least I have to see the experiences)
  eps_end: 0.005
  annealing_frames: 520_000 
  init_random_frames: 20_000
  frame_skip: 4

# policy
policy:
  type: "CNN_MLP"
  cnn_net:
    num_cells: [32, 64, 64] # number of kernel per layer
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  mlp_net:
    num_cells: [64, 64]  # Number of units per layer
  activation: "ReLU"  # Activation function used in the layers
  use_batch_norm: False

# buffer
buffer:
  buffer_size: 100_000
  batch_size: 256
  scratch_dir: null
  prioritized_replay: False
  alpha: 0.6
  beta: 0.4

# logger
logger:
  backend: wandb
  project_name: dqn_pixels_cartpolev0_sweep
  group_name: null
  test_interval: 25_000
  num_test_episodes: 5
  video: False
  mode: "online" # "online" or "disabled" ("offline" too but not used)
  save_model: False
  save_distributions: False
  
# Optim
optim:
  lr: 0.0015 # 0.002
  max_grad_norm: 10
  weight_decay: 0.00001
  eps: 1.5e-4 # default: 1e-08 # rainbow 1.5e-4
  scheduler:
    active: False
    type: "stepLR"
    gamma: 0.4
    step_size: 500_000

# loss
loss:
  gamma: 0.99
  target_updater:
    type: "hard"
    hard_update_freq: 50  
    num_updates: 1

  # target_updater:
  #   type: "soft"
  #   eps: 0.995 #0.995 # eps = 1 - tau # Check 0.98
  #   num_updates: 8
