  
device: null

# Environment
# SEEDS: [118398, 676190, 786456, 171936, 887739, 919409, 711872, 442081, 189061, 117840]
env:
  env_name: CartPole-v1
  seed: 118398

# collector
collector:
  total_frames: 350_100
  frames_per_batch: 10
  eps_start: 1.0
  eps_end: 0.05
  annealing_frames: 250_000
  init_random_frames: 10_000

# buffer
buffer:
  buffer_size: 10_000
  batch_size: 128

# logger
logger:
  backend: wandb
  project_name: torchrl_example_dqn
  group_name: DQN_CartPole_v1_ER
  exp_name: DQN
  test_interval: 50_000
  num_test_episodes: 5
  video: False

# Optim
optim:
  lr: 2.5e-4
  max_grad_norm: 10

# loss
loss:
  gamma: 0.99
  hard_update_freq: 50
  num_updates: 1
