device: null

# Environment
# SEEDS: [118398, 676190, 786456, 171936, 887739, 919409, 711872, 442081, 189061, 117840]
env:
  env_name: CartPole-v1
  seed: 118398

# Collector
collector:
  total_frames: 350_100
  frames_per_batch: 250
  eps_start: 1.0
  eps_end: 0.01  # More common endpoint for epsilon decay
  annealing_frames: 200_000  # Slightly faster decay
  init_random_frames: 10_000

# Policy
policy:
  type: "MLP"  # Example type, adjust based on your architecture (e.g., CNN, RNN)
  layers: [64, 64]  # Common architecture for CartPole
  activation: "ReLU"  # Activation function used in the layers

# Buffer
buffer:
  buffer_size: 50_000  # Larger buffer size for better sampling
  batch_size: 32  # Common batch size in many implementations
  prioritized_replay: False  # Disable prioritized replay
  alpha: 0.7
  beta: 0.5

# Logger
logger:
  backend: wandb
  project_name: BER_final_project
  group_name: DQN_CartPole_v1_ER
  exp_name: DQN
  test_interval: 10_000  # More frequent testing
  num_test_episodes: 10  # More test episodes for better evaluation
  video: False

# Optimizer
optim:
  lr: 1e-4  # Lower learning rate for more stable training
  max_grad_norm: 10

# Loss
loss:
  gamma: 0.99
  hard_update_freq: 10_000  # More stable updates with a larger update frequency
  num_updates: 50  # Fewer updates per step
